name: minimind
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - comm=0.2.3
  - cpython=3.12.12
  - debugpy=1.8.19
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.1
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.10.1
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.5.0
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - blinker==1.9.0
      - boto3==1.42.36
      - botocore==1.42.36
      - cachetools==6.2.6
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==3.6.0
      - datasketch==1.6.4
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - filelock==3.20.3
      - flask==3.0.3
      - flask-cors==4.0.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - itsdangerous==2.2.0
      - jieba==0.42.1
      - jinja2==3.1.2
      - jiter==0.12.0
      - jmespath==1.1.0
      - joblib==1.5.3
      - jsonlines==4.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.22.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.16
      - narwhals==2.15.0
      - networkx==3.6.1
      - ngrok==1.4.0
      - nltk==3.8
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.590.48
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.59.6
      - pandas==2.3.3
      - peft==0.7.1
      - pillow==11.3.0
      - prettytable==3.17.0
      - propcache==0.4.1
      - protobuf==5.29.5
      - psutil==5.9.8
      - pyarrow==23.0.0
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyecharts==2.0.9
      - pynvml==13.0.1
      - pyparsing==3.3.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rich==13.7.1
      - rpds-py==0.30.0
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scikit-learn==1.5.1
      - scipy==1.17.0
      - sentence-transformers==2.3.1
      - sentencepiece==0.2.1
      - sentry-sdk==2.51.0
      - setproctitle==1.3.7
      - simhash==2.1.2
      - simplejson==3.20.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - streamlit==1.50.0
      - swankit==0.2.4
      - swanlab==0.6.8
      - sympy==1.13.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.10.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.2.0
      - trl==0.13.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - ujson==5.1.0
      - urllib3==2.6.3
      - wandb==0.18.3
      - watchdog==6.0.0
      - werkzeug==3.1.5
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/lott/miniconda3/envs/minimind
